"""initial schema

Revision ID: 3b1ae07eb65a
Revises: 
Create Date: 2026-09-11 20:27:19.539171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1ae07eb65a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('base_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('index_constituents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('change', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('change_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_free_float_market_cap', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('divisor', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('total_market_cap', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('free_float_marlet_cap', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('impact_cost', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('issued_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_data')
    op.drop_table('index_value')
    op.drop_table('index_daily')
    op.drop_table('index_constituents')
    op.drop_table('security')
    op.drop_table('indices')
    # ### end Alembic commands ###
