"""make constituent weight nullable

Revision ID: 8103029df586
Revises: b01aa6ec05a5
Create Date: 2026-09-15 23:47:23.211983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8103029df586'
down_revision: Union[str, Sequence[str], None] = 'b01aa6ec05a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('index_constituents', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('market_data', sa.Column('free_float_market_cap', sa.Numeric(precision=20, scale=4), nullable=False))
    op.drop_column('market_data', 'free_float_marlet_cap')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('free_float_marlet_cap', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=False))
    op.drop_column('market_data', 'free_float_market_cap')
    op.alter_column('index_constituents', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
