"""added indeX_value attribute

Revision ID: b01aa6ec05a5
Revises: 35f16cca265f
Create Date: 2026-09-11 22:33:35.035727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01aa6ec05a5'
down_revision: Union[str, Sequence[str], None] = '35f16cca265f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_value', sa.Column('index_value', sa.Numeric(precision=20, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_value', 'index_value')
    # ### end Alembic commands ###
